config/routes.rb
Rails.application.routes.draw do
  resources :clases
  resources :typeindices
  resources :administratives do
    collection do
      get :filtered
    end
  end
  resources :indices
  resources :postedepaies
  resources :typedetablissements
  resources :conjoints
  resources :enfants
  resources :billeteurs
  resources :agences
  resources :banques
  resources :titres
  resources :sexes
  resources :mariers
  devise_for :users, path: '', path_names: {sign_in: 'Login', sign_out: 'Logout', sign_up: 'Register'}
  get 'pages/home'
  get 'pages/index'
  get 'pages/grappe_familliale'
  resources :emplois
  #resources :preststions
  resources :prestations
  resources :expatries
  resources :residences
  resources :agents do
    collection do
      get :agencebybanque
    end
    collection do
      get :departementbyregion
    end
  end
  resources :positions
  resources :postes
  resources :echellons
  resources :corps
  resources :classes
  resources :grades
  resources :mode_paiements
  resources :sous_service_etablsmts
  resources :service_etablsmts
  resources :etablissements
  resources :services
  resources :typeservices
  resources :directions
  resources :departements
  resources :regions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
end

app/models/agence.rb
class Agence < ApplicationRecord
  belongs_to :banque

  validates_presence_of :name, :code_agence, :banque_id
end

app/models/agent.rb
class Agent < ApplicationRecord
    belongs_to :marier
    belongs_to :titre
    belongs_to :sexe
    belongs_to :region
    #belongs_to :departement
    belongs_to :mode_paiement
    belongs_to :banque, optional: :true
    belongs_to :agence, optional: :true
    belongs_to :billeteur, optional: :true
    
    has_many :enfants
    has_many :conjoints

    validates_presence_of :matricule, :nom, :prenom, :date_naissance, :date_recrutement, :lieu_naissance, :nationalite, :email, :telephone, :adresse, :marier_id, :titre_id, :sexe_id, :region_id, :mode_paiement_id
end

app/models/banque.rb
class Banque < ApplicationRecord
    has_many :agents

  validates_presence_of :name, :code

end

app/models/clase.rb
class Clase < ApplicationRecord
  #belongs_to :grade

  #has_many :echellons

  validates_presence_of :name, :echellon_id
end

app/models/classe.rb
class Classe < ApplicationRecord
  #belongs_to :echellon
end

app/models/conjoint.rb
class Conjoint < ApplicationRecord
  belongs_to :agent

  validates_presence_of :nom, :prenom, :photo_certificat_mariage, :numero_de_reference, :date_mariage, :agent_id

end

app/models/corp.rb
class Corp < ApplicationRecord
    #belongs_to :grade
    
    validates_presence_of :code, :name
end

app/models/echellon.rb
class Echellon < ApplicationRecord
    #belongs_to :clase

    #has_one :indice

    validates_presence_of :code #, :clase_id
    
end

app/models/emploi.rb
class Emploi < ApplicationRecord
    belongs_to :service
    
    validates_presence_of :name, :service_id

end

app/models/enfant.rb
class Enfant < ApplicationRecord
  belongs_to :agent

  validates_presence_of :nom, :prenom, :date_naissance, :agent_id
end

app/models/expatrie.rb
class Expatrie < ApplicationRecord
end

app/models/grade.rb
class Grade < ApplicationRecord
  #has_many :corps
  #has_many :clases

  #belongs_to : administrative

  validates_presence_of :code #, :clase_id , :corp_id
end

app/models/indice.rb
class Indice < ApplicationRecord
    #has_many :grades
    #belongs_to :typeindice
    #belongs_to :echellon
    validates_presence_of :name, :typeindice_id #, :echellon_id
end

app/models/marier.rb
class Marier < ApplicationRecord

    validates_presence_of :name
    
end

app/models/position.rb
class Position < ApplicationRecord
end

app/models/poste.rb
class Poste < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
    has_many :departements
    has_many :etablissements

    validates_presence_of :name
end

app/models/service.rb
class Service < ApplicationRecord
    belongs_to :etablissement
    
    has_many :emplois

    validates_presence_of :name, :etablissement_id
end

app/models/sexe.rb
class Sexe < ApplicationRecord
    has_many :agents
    validates_presence_of :name
end

app/models/titre.rb
class Titre < ApplicationRecord
    has_many :agents
    validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :agent_de_saisie], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/enfants_controller.rb
class EnfantsController < ApplicationController
  before_action :set_enfant, only: [:show, :edit, :update, :destroy]
  access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all

  # GET /enfants
  def index
    @id_agent = params["id_agent"]
    session[:id_agent] = @id_agent if !@id_agent.nil?
  
   # @enfants = Enfant.all
    
    #@IDenfant = Enfant.find(params["enfantId"]) if  !@IDenfant.nil?
    @enfants = Enfant.where(agent_id: session[:id_agent])
    
  end

  # GET /enfants/1
  def show
  end

  # GET /enfants/new
  def new
    @enfant = Enfant.new
    #@id_agent = params["id_agent"]
    
  end

  # GET /enfants/1/edit
  def edit
  end

  # POST /enfants
  def create
    @enfant = Enfant.new(enfant_params)
    @enfant.agent_id = session[:id_agent]
    
    if @enfant.save
      redirect_to @enfant, notice: 'Enfant was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /enfants/1
  def update
    if @enfant.update(enfant_params)
      redirect_to @enfant, notice: 'Enfant was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /enfants/1
  def destroy
    @enfant.destroy
    redirect_to enfants_url, notice: 'Enfant was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enfant
      @enfant = Enfant.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def enfant_params
      params.require(:enfant).permit(:nom, :prenom, :date_naissance, :agent_id)
    end
end

app/helpers/enfants_helper.rb
module EnfantsHelper
end

app/views/enfants/_form.html.erb
<main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
  <%= form_with(model: enfant, local: true) do |form| %>
    <% if enfant.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(enfant.errors.count, "error") %> prohibited this enfant from being saved:</h2>

        <ul>
        <% enfant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :nom %>
      <%= form.text_field :nom, class:"form-control col-md-3" %>
    </div>

    <div class="form-group">
      <%= form.label :prenom %>
      <%= form.text_field :prenom, class:"form-control col-md-3" %>
    </div>

    <div class="form-group">
      <%= form.label :date_naissance %>
      <%= form.date_field :date_naissance, class:"form-control col-md-3" %>
    </div>

    <div class="form-group" style="display:none">
      <%= form.label :agent_id %>
      <%= form.text_field :agent_id, class:"form-control col-md-3" %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

</main>

app/views/enfants/edit.html.erb
<main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
    <h1>Editing Enfant</h1>

    <%= render 'form', enfant: @enfant %>

    <%= link_to 'Show', @enfant %> |
    <%= link_to 'Back', enfants_path %>

</main>

app/views/enfants/index.html.erb
<main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
  <p id="notice"><%= notice %></p>

  <h1>Enfants</h1>

  <table>
    <thead>
      <tr>
        <th>Nom</th>
        <th>Prenom</th>
        <th>Date naissance</th>
        <th>Agent</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @enfants.each do |enfant| %>
        <tr>
          <td><%= enfant.nom %></td>
          <td><%= enfant.prenom %></td>
          <td><%= enfant.date_naissance %></td>
          <td><%= enfant.agent.matricule %></td>
          <td><%= link_to 'Show', enfant %></td>
          <td><%= link_to 'Edit', edit_enfant_path(enfant) %></td>
          <td><%= link_to 'Destroy', enfant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Enfant', new_enfant_path() %>

</main>

app/views/enfants/new.html.erb
<main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
    <h1>New Enfant</h1>

    <%= render 'form', enfant: @enfant %>

    <%= link_to 'Back', enfants_path %>

</main>

app/views/enfants/show.html.erb
<main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
  <p id="notice"><%= notice %></p>
  <h3>Enfant de l'agent:  <strong><%= @enfant.agent.nom + " " + @enfant.agent.prenom + " (" +  @enfant.agent.matricule + ") " %></strong></h3>
  <p>
    <strong>Nom:</strong>
    <%= @enfant.nom %>
  </p>

  <p>
    <strong>Prenom:</strong>
    <%= @enfant.prenom %>
  </p>

  <p>
    <strong>Date naissance:</strong>
    <%= @enfant.date_naissance %>
  </p>

  <p>
    
    <p></p>
    <p></p>
  </p>

  <%= link_to 'Edit', edit_enfant_path(@enfant) %> |
  <%= link_to 'Back', enfants_path() %>

</main>