config/routes.rb
Rails.application.routes.draw do
  resources :clases
  resources :typeindices
  resources :administratives do
    collection do
      get :filtered
    end
  end
  resources :indices
  resources :postedepaies
  resources :typedetablissements
  resources :conjoints
  resources :enfants
  resources :billeteurs
  resources :agences
  resources :banques
  resources :titres
  resources :sexes
  resources :mariers
  devise_for :users, path: '', path_names: {sign_in: 'Login', sign_out: 'Logout', sign_up: 'Register'}
  get 'pages/home'
  get 'pages/index'
  get 'pages/grappe_familliale'
  resources :emplois
  #resources :preststions
  resources :prestations
  resources :expatries
  resources :residences
  resources :agents do
    collection do
      get :agencebybanque
    end
    collection do
      get :departementbyregion
    end
  end
  resources :positions
  resources :postes
  resources :echellons
  resources :corps
  resources :classes
  resources :grades
  resources :mode_paiements
  resources :sous_service_etablsmts
  resources :service_etablsmts
  resources :etablissements
  resources :services
  resources :typeservices
  resources :directions
  resources :departements
  resources :regions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
end

app/models/agence.rb
class Agence < ApplicationRecord
  belongs_to :banque

  validates_presence_of :name, :code_agence, :banque_id
end

app/models/agent.rb
class Agent < ApplicationRecord
    belongs_to :marier
    belongs_to :titre
    belongs_to :sexe
    belongs_to :region
    #belongs_to :departement
    belongs_to :mode_paiement
    belongs_to :banque, optional: :true
    belongs_to :agence, optional: :true
    belongs_to :billeteur, optional: :true
    
    has_many :enfants
    has_many :conjoints

    validates_presence_of :matricule, :nom, :prenom, :date_naissance, :date_recrutement, :lieu_naissance, :nationalite, :email, :telephone, :adresse, :marier_id, :titre_id, :sexe_id, :region_id, :mode_paiement_id
end

app/models/banque.rb
class Banque < ApplicationRecord
    has_many :agents

  validates_presence_of :name, :code

end

app/models/clase.rb
class Clase < ApplicationRecord
  #belongs_to :grade

  #has_many :echellons

  validates_presence_of :name, :echellon_id
end

app/models/classe.rb
class Classe < ApplicationRecord
  #belongs_to :echellon
end

app/models/conjoint.rb
class Conjoint < ApplicationRecord
  belongs_to :agent

  validates_presence_of :nom, :prenom, :photo_certificat_mariage, :numero_de_reference, :date_mariage, :agent_id

end

app/models/corp.rb
class Corp < ApplicationRecord
    #belongs_to :grade
    
    validates_presence_of :code, :name
end

app/models/echellon.rb
class Echellon < ApplicationRecord
    #belongs_to :clase

    #has_one :indice

    validates_presence_of :code #, :clase_id
    
end

app/models/emploi.rb
class Emploi < ApplicationRecord
    belongs_to :service
    
    validates_presence_of :name, :service_id

end

app/models/enfant.rb
class Enfant < ApplicationRecord
  belongs_to :agent

  validates_presence_of :nom, :prenom, :date_naissance, :agent_id
end

app/models/expatrie.rb
class Expatrie < ApplicationRecord
end

app/models/grade.rb
class Grade < ApplicationRecord
  #has_many :corps
  #has_many :clases

  #belongs_to : administrative

  validates_presence_of :code #, :clase_id , :corp_id
end

app/models/indice.rb
class Indice < ApplicationRecord
    #has_many :grades
    #belongs_to :typeindice
    #belongs_to :echellon
    validates_presence_of :name, :typeindice_id #, :echellon_id
end

app/models/marier.rb
class Marier < ApplicationRecord

    validates_presence_of :name
    
end

app/models/poste.rb
class Poste < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
    has_many :departements
    has_many :etablissements

    validates_presence_of :name
end

app/models/service.rb
class Service < ApplicationRecord
    belongs_to :etablissement
    
    has_many :emplois

    validates_presence_of :name, :etablissement_id
end

app/models/sexe.rb
class Sexe < ApplicationRecord
    has_many :agents
    validates_presence_of :name
end

app/models/titre.rb
class Titre < ApplicationRecord
    has_many :agents
    validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :agent_de_saisie], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/classes_controller.rb
class ClassesController < ApplicationController
  before_action :set_class, only: [:show, :edit, :update, :destroy]
  access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all

  # GET /classes
  def index
    @classes = Classe.all
  end

  # GET /classes/1
  def show
  end

  # GET /classes/new
  def new
    @class = Classe.new
  end

  # GET /classes/1/edit
  def edit
  end

  # POST /classes
  def create
    @class = Classe.new(class_params)

    if @class.save
      redirect_to @class, notice: 'Classe was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /classes/1
  def update
    if @class.update(class_params)
      redirect_to @class, notice: 'Classe was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /classes/1
  def destroy
    @class.destroy
    redirect_to classes_url, notice: 'Classe was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_class
      @class = Classe.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def class_params
      params.require(:class).permit(:name, :echellon_id)
    end
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/views/classes/_form.html.erb
<main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
  <%= form_with(model: classe, local: true) do |form| %>
    <% if classe.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(classe.errors.count, "error") %> prohibited this classe from being saved:</h2>

        <ul>
        <% classe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class:"form-control col-md-3" %>
    </div>

    <div class="field">
      <%= form.label :echellon_id %>
      <%= form.text_field :echellon_id %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</main>

app/views/classes/edit.html.erb
<main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
    <h1>Editing Class</h1>

    <%= render 'form', class: @class %>

    <%= link_to 'Show', @class %> |
    <%= link_to 'Back', classes_path %>
</main>

app/views/classes/index.html.erb
<main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
  <p id="notice"><%= notice %></p>

  <h1>Classes</h1>

    <% @classes.each do |classe| %>
      <div class="card text-center">  
        <div class="card-header">
          <span>Indice</span>
        </div>
        <div class="card-body">
          <h2 class="card-title"><%= classe.name%></h2>
          <div class="row">
            <div class="col-md-6">
              <p class="card-text" style=text-align:left; ></p>
              <p class="card-text" style=text-align:left; >Echellon : <%= classe.echellon.code %></p>
            </div>
            <div class="col-md-6">
              <p class="card-text" style=text-align:right; ></p>
            </div>
          </div>
          <!-- a href="#" class="btn btn-primary">Go somewhere</a -->
        </div>
        <div class="card-footer text-muted">
          <span>DTAI-CEP</span>
          <span style=margin:auto;><%= link_to 'Voir', classe %></span>
          <span style=margin:auto;><%= link_to 'Editer', edit_classe_path(classe) %></span>
          <span style=margin:auto;><%= link_to 'Destroy', classe, method: :delete, data: { confirm: 'Are you sure?' } %></span>
          </div>
      </div> 
      
    <br>
    <% end %>
  

  <%= link_to 'New Class', new_class_path %>
</main>

app/views/classes/new.html.erb
<h1>New Class</h1>

<%= render 'form', class: @class %>

<%= link_to 'Back', classes_path %>

app/views/classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @class.name %>
</p>

<p>
  <strong>Echellon:</strong>
  <%= @class.echellon %>
</p>

<%= link_to 'Edit', edit_class_path(@class) %> |
<%= link_to 'Back', classes_path %>