config/routes.rb
Rails.application.routes.draw do
  resources :clases
  resources :typeindices
  resources :administratives do
    collection do
      get :filtered
    end
  end
  resources :indices
  resources :postedepaies
  resources :typedetablissements
  resources :conjoints
  resources :enfants
  resources :billeteurs
  resources :agences
  resources :banques
  resources :titres
  resources :sexes
  resources :mariers
  devise_for :users, path: '', path_names: {sign_in: 'Login', sign_out: 'Logout', sign_up: 'Register'}
  get 'pages/home'
  get 'pages/index'
  get 'pages/grappe_familliale'
  resources :emplois
  #resources :preststions
  resources :prestations
  resources :expatries
  resources :residences
  resources :agents do
    collection do
      get :agencebybanque
    end
    collection do
      get :departementbyregion
    end
  end
  resources :positions
  resources :postes
  resources :echellons
  resources :corps
  resources :classes
  resources :grades
  resources :mode_paiements
  resources :sous_service_etablsmts
  resources :service_etablsmts
  resources :etablissements
  resources :services
  resources :typeservices
  resources :directions
  resources :departements
  resources :regions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
end

app/models/agence.rb
class Agence < ApplicationRecord
  belongs_to :banque

  validates_presence_of :name, :code_agence, :banque_id
end

app/models/agent.rb
class Agent < ApplicationRecord
    belongs_to :marier
    belongs_to :titre
    belongs_to :sexe
    belongs_to :region
    #belongs_to :departement
    belongs_to :mode_paiement
    belongs_to :banque, optional: :true
    belongs_to :agence, optional: :true
    belongs_to :billeteur, optional: :true
    
    has_many :enfants
    has_many :conjoints

    validates_presence_of :matricule, :nom, :prenom, :date_naissance, :date_recrutement, :lieu_naissance, :nationalite, :email, :telephone, :adresse, :marier_id, :titre_id, :sexe_id, :region_id, :mode_paiement_id
end

app/models/banque.rb
class Banque < ApplicationRecord
    has_many :agents

  validates_presence_of :name, :code

end

app/models/clase.rb
class Clase < ApplicationRecord
  #belongs_to :grade

  #has_many :echellons

  validates_presence_of :name, :echellon_id
end

app/models/classe.rb
class Classe < ApplicationRecord
  #belongs_to :echellon
end

app/models/conjoint.rb
class Conjoint < ApplicationRecord
  belongs_to :agent

  validates_presence_of :nom, :prenom, :photo_certificat_mariage, :numero_de_reference, :date_mariage, :agent_id

end

app/models/corp.rb
class Corp < ApplicationRecord
    #belongs_to :grade
    
    validates_presence_of :code, :name
end

app/models/echellon.rb
class Echellon < ApplicationRecord
    #belongs_to :clase

    #has_one :indice

    validates_presence_of :code #, :clase_id
    
end

app/models/emploi.rb
class Emploi < ApplicationRecord
    belongs_to :service
    
    validates_presence_of :name, :service_id

end

app/models/enfant.rb
class Enfant < ApplicationRecord
  belongs_to :agent

  validates_presence_of :nom, :prenom, :date_naissance, :agent_id
end

app/models/expatrie.rb
class Expatrie < ApplicationRecord
end

app/models/grade.rb
class Grade < ApplicationRecord
  #has_many :corps
  #has_many :clases

  #belongs_to : administrative

  validates_presence_of :code #, :clase_id , :corp_id
end

app/models/indice.rb
class Indice < ApplicationRecord
    #has_many :grades
    #belongs_to :typeindice
    #belongs_to :echellon
    validates_presence_of :name, :typeindice_id #, :echellon_id
end

app/models/marier.rb
class Marier < ApplicationRecord

    validates_presence_of :name
    
end

app/models/position.rb
class Position < ApplicationRecord
end

app/models/poste.rb
class Poste < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
    has_many :departements
    has_many :etablissements

    validates_presence_of :name
end

app/models/service.rb
class Service < ApplicationRecord
    belongs_to :etablissement
    
    has_many :emplois

    validates_presence_of :name, :etablissement_id
end

app/models/sexe.rb
class Sexe < ApplicationRecord
    has_many :agents
    validates_presence_of :name
end

app/models/titre.rb
class Titre < ApplicationRecord
    has_many :agents
    validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :agent_de_saisie], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/mariers_controller.rb
class MariersController < ApplicationController
  before_action :set_marier, only: [:show, :edit, :update, :destroy]
  access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all

  # GET /mariers
  def index
    @mariers = Marier.all
  end

  # GET /mariers/1
  def show
  end

  # GET /mariers/new
  def new
    @marier = Marier.new
  end

  # GET /mariers/1/edit
  def edit
  end

  # POST /mariers
  def create
    @marier = Marier.new(marier_params)

    if @marier.save
      redirect_to @marier, notice: 'Marier was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /mariers/1
  def update
    if @marier.update(marier_params)
      redirect_to @marier, notice: 'Marier was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /mariers/1
  def destroy
    @marier.destroy
    redirect_to mariers_url, notice: 'Marier was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marier
      @marier = Marier.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def marier_params
      params.require(:marier).permit(:name)
    end
end

app/helpers/mariers_helper.rb
module MariersHelper
end

app/views/mariers/_form.html.erb
<main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
  <%= form_with(model: marier, local: true) do |form| %>
    <% if marier.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(marier.errors.count, "error") %> prohibited this marier from being saved:</h2>

        <ul>
        <% marier.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</main>

app/views/mariers/edit.html.erb
<main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
    <h1>Editing Marier</h1>

    <%= render 'form', marier: @marier %>

    <%= link_to 'Show', @marier %> |
    <%= link_to 'Back', mariers_path %>
</main>

app/views/mariers/index.html.erb
<main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
  <p id="notice"><%= notice %></p>

  <h1>Mariers</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @mariers.each do |marier| %>
        <tr>
          <td><%= marier.name %></td>
          <td><%= link_to 'Show', marier %></td>
          <td><%= link_to 'Edit', edit_marier_path(marier) %></td>
          <td><%= link_to 'Destroy', marier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Marier', new_marier_path %>
</main>

app/views/mariers/new.html.erb
<main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
    <h1>New Marier</h1>

    <%= render 'form', marier: @marier %>

    <%= link_to 'Back', mariers_path %>
<main>

app/views/mariers/show.html.erb
<main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @marier.name %>
  </p>

  <%= link_to 'Edit', edit_marier_path(@marier) %> |
  <%= link_to 'Back', mariers_path %>
</main>